name: Main workflow

on:
  push:
on: [push, pull_request]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
        runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Get dependencies
      run: go mod download
    
    - name: Build
      run: make build
    
    - name: Translate Issues
      uses: usthe/issues-translate-action@v2.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Ensure that the GITHUB_TOKEN secret is set in the repository settings.
        # The token should be a GitHub personal access token with the necessary permissions for the GitHub action.
        TARGET_LANGUAGE: 'eng'
        # Ensure that the GITHUB_TOKEN secret is set in the repository settings.
        # The token should be a GitHub personal access token with the necessary permissions for the GitHub action.

    - name: Lint
      run: make lint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Ensure that the GITHUB_TOKEN secret is set in the repository settings.
        # The token should be a GitHub personal access token with the necessary permissions for the GitHub action.

    - name: Test
      run: make test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
